services:
  consumer:
    container_name: consumer
    tty: true
    build:
      context: .
      dockerfile: .docker/node/dev/Dockerfile
    command: ["npm", "run", "start:consumer"]
    volumes:
      - ./:/app
    environment:
      ENV RUNNING_ENV: "prod"
