services:
  consumer:
    container_name: consumer
    tty: true
    build:
      context: .
      dockerfile: .docker/node/dev/Dockerfile
    command: ["npm", "run", "start:consumer"]
    volumes:
      - ./:/app
    env_file:
      - .env
      

