apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: resize-consumer
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: resize-consumer
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - src/index.js
            image: 317884193661.dkr.ecr.eu-west-1.amazonaws.com/resize-config:894d86635e2c51dbe0d76f2d8a90308a09c7d597
            name: resize-consumer
            resources: {}
            env:
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: resize-secret
                  key: AWS_DEFAULT_REGION
            - name: QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: resize-secret
                  key: QUEUE_NAME
            - name: QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: resize-secret
                  key: QUEUE_URL
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: resize-secret
                  key: BUCKET_NAME
            - name: BUCKET_NAME_TMP
              valueFrom:
                secretKeyRef:
                  name: resize-secret
                  key: BUCKET_NAME_TMP
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
