apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: resize-consumer
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: resize-consumer
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          serviceAccountName: s3-account
          containers:
          - image: 317884193661.dkr.ecr.eu-west-1.amazonaws.com/resize-cluster:e77f11e01a768a85006aa785684a0bf98eed7e4e
            name: resize-consumer
            command: ["node", "index.js"] 
            resources: {}
            env:
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: resize-cm
                  key: AWS_DEFAULT_REGION
            - name: QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: resize-cm
                  key: QUEUE_NAME
            - name: QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: resize-cm
                  key: QUEUE_URL
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: resize-cm
                  key: BUCKET_NAME
            - name: BUCKET_NAME_TMP
              valueFrom:
                configMapKeyRef:
                  name: resize-cm
                  key: BUCKET_NAME_TMP
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
